<?php require_once "../includes/db.php"; ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>JARVIS AGI</title>
<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;600;700&family=Inter:wght@400;500&display=swap" rel="stylesheet">
<style>:root{--bg:#080d0b;--card:#111d17;--green:#22c55e;--text:#ecfdf5;--border:rgba(34,197,94,0.12)}body{font-family:'Inter',sans-serif;background:var(--bg);color:var(--text);margin:0;display:flex}.sidebar{width:250px;background:#080f0b;padding:20px}.main{flex:1;padding:30px}.card{background:var(--card);padding:20px;border-radius:12px;border:1px solid var(--border)}.nav-link{display:block;padding:12px;margin:8px 0;background:var(--card);color:var(--text);border-radius:8px;text-decoration:none}.nav-link:hover{background:var(--green);color:var(--bg)}.dot{width:12px;height:12px;background:var(--green);border-radius:50%;animation:pulse 2s infinite}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}.messages{height:400px;overflow-y:auto;margin-bottom:15px;padding:15px;background:var(--bg);border-radius:8px}.msg{margin:10px 0}.msg.user{text-align:right}.msg-content{display:inline-block;padding:10px 15px;border-radius:8px;max-width:70%}.msg.user .msg-content{background:var(--green);color:var(--bg)}.msg.bot .msg-content{background:var(--card);border:1px solid var(--border)}</style></head><body>
<div class="sidebar"><div style="font-family:'Space Grotesk',sans-serif;font-size:1.5rem;color:var(--green);margin-bottom:30px">AgroTech</div>
<a href="dashboard.php" class="nav-link">Dashboard</a><a href="fcr.php" class="nav-link">FCR Calculator</a><a href="jarvis.php" class="nav-link">JARVIS AGI</a></div>
<div class="main"><h1 style="font-family:'Space Grotesk',sans-serif;color:var(--green)">JARVIS AGI Assistant</h1>
<div class="card"><div style="display:flex;align-items:center;gap:10px;margin-bottom:15px"><div class="dot"></div><span>AGI Online - Port 5052</span></div>
<div class="messages"><div class="msg bot"><div class="msg-content">Hello Richard! I'm JARVIS AGI, your poultry farm assistant. How can I help?</div></div></div>
<div style="display:flex;gap:10px"><input id="input" type="text" placeholder="Ask about your farm..." style="flex:1;padding:12px;border-radius:8px;border:1px solid var(--border);background:var(--bg);color:var(--text)"><button onclick="send()" style="padding:12px 24px;border:none;border-radius:8px;background:var(--green);color:var(--bg);font-weight:600;cursor:pointer">Send</button></div></div></div>
<script>function send(){const i=document.getElementById('input');if(!i.value.trim())return;const m=document.querySelector('.messages');m.innerHTML+='<div class=\"msg user\"><div class=\"msg-content\">'+i.value+'</div></div>';i.value='';m.scrollTop=m.scrollHeight;setTimeout(()=>{m.innerHTML+='<div class=\"msg bot\"><div class=\"msg-content\">Connect to port 5052 for live AGI response.</div></div>';m.scrollTop=m.scrollHeight},1000)}</script></body></html>